version: '3'

services:
  jenkins:
    privileged: true
    build: .
    image: emnify/jenkins-casc:latest
    env_file:
      - jenkins.env
    volumes:
      - ./my_marvin.yml:/var/jenkins_casc.yml
    ports:
      - "8080:8080"
    environment:
      USER_CHOCOLATEEN_PASSWORD: "lopes"
      USER_VAUGIE_G_PASSWORD: "lopes"
      USER_I_DONT_KNOW_PASSWORD: "lopes"
      USER_NASSO_PASSWORD: "lopes"